name: Production Track Test



on: 
  workflow_dispatch:

jobs:
  testtracks:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Validate tracks
        run: chmod +x ./.github/scripts/production.sh; ./.github/scripts/production.sh
        env:
          TOKEN: ${{ secrets.TOKEN }}
