name: Production Track Test

env:
  TOKEN: ${{ secrets.TOKEN }}

on: 
  workflow_dispatch:

jobs:
  testtracks:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Generate array of tracks
        run: |
          for dir in tracks/ ; do
            cd $dir
            docker run -e INSTRUQT_TOKEN=${{ env.TOKEN }} --mount type=bind,source="$(pwd)",target=/track instruqt/cli track validate
          done
