name: Production Track Test

env:
  TOKEN: ${{ secrets.TOKEN }}

on: 
  workflow_dispatch:

jobs:
  generate_slugs:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Generate array of tracks
        run: chmod +x ./.github/scripts/production.sh; ./.github/scripts/production.sh
